version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - dev
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
  
dotnet_csproj:
  patch: true
  file: 'src\UI\Medium\Medium.csproj'
  version: $(commit_description)
  
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Medium.sln --verbosity m
 
test_script:
  - cmd: dotnet restore ./tests/Medium.Services.Tests/Medium.Services.Tests.csproj
  - cmd: dotnet test ./tests/Medium.Services.Tests/Medium.Services.Tests.csproj
  
artifacts:
 - path: '\src\bin\Debug\netcoreapp1.1\publish'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
on_finish :
deploy: off