version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - dev
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
  
dotnet_csproj:
  patch: true
  file: 'src\UI\Medium\Medium.csproj'
  version: $(commit_description)
  
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/UI/Medium/Medium.csproj --verbosity m
 
test_script:
  - cmd: dotnet restore ./tests/MediumTests.csproj
  - cmd: dotnet test ./tests/MediumTests.csproj
  
artifacts:
 - path: '\src\bin\Debug\netcoreapp1.1\publish'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off